unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"
bind \` switch-client -t'{marked}'
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
bind "|" split-window -h -c "#{pane_current_path}"
bind "\\" split-window -fh -c "#{pane_current_path}"
bind "-" split-window -v -c "#{pane_current_path}"
bind "_" split-window -fv -c "#{pane_current_path}"
set -g mouse on
set-option -g history-limit 5000
bind -r "<" swap-window -d -t -1
bind -r ">" swap-window -d -t +1
bind c new-window -c "#{pane_current_path}"
bind Space last-window
bind C-SPace switch-client -l

bind -r C-j resize-pane -D 15
bind -r C-k resize-pane -U 15
bind -r C-h resize-pane -L 15
bind -r C-l resize-pane -R 15

bind-key h split-window -h "nvim ~/scratch/notes.md"
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
run '~/.config/tmux/plugins/tpm/tpm'
